version: "3.9"

services:

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: main:latest
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities:
    #           - gpu
    ports:
      - 80:80
    volumes:
      - /Users/michaelmcguire/jet_engine_rul:/root/a/folder
    restart: on-failure
    user: "root"
    command: "gunicorn -b 0.0.0.0:80 application:application"
  